version: '3.5'

services:
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: erp-redis-commander
    ports:
      - 8082:8081
    environment:
      REDIS_HOST: redis:6379
    networks:
      - rdnet
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: erp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: always
