version: '3.5'

services:
  postgres:
    image: postgres:10.0-alpine
    volumes:
      - ./docker-postgres-databases.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/postgres/data
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: dev
      PGDATA: /postgres/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    restart: always

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    restart: always
    networks:
      - rdnet

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - 8082:8081
    environment:
      REDIS_HOST: redis:6379
    networks:
      -rdnet
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
  rdnet:

volumes:
  postgres:
  pgadmin: