version: '3.5'

services:
  erp-application:
    build: .
    container_name: erp-application
    ports:
      - 8080:8080
    networks:
      - postgres
      - rdnet
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:10.0-alpine
    container_name: erp-postgre
    volumes:
      - ./docker-postgres-databases.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/postgres/data
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: dev
      PGDATA: /postgres/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - postgres
    restart: always

  redis:
    image: redis:alpine
    container_name: erp-redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - rdnet

networks:
  postgres:
  rdnet:

volumes:
  postgres:
  pgadmin: